(* autogenerated from unicode/utf8 *)

From New.golang Require Import defn.
Require Export New.trusted_code.unicode.utf8.
Import utf8.
Definition utf8 : go_string := "unicode/utf8".

Module utf8.

Module acceptRange. Definition id : go_string := "unicode/utf8.acceptRange"%go. End acceptRange.

Section code.
Context `{ffi_syntax}.


Axiom RuneError : val.

Axiom RuneSelf : Z.

Axiom MaxRune : val.

Axiom UTFMax : Z.

Axiom surrogateMin : Z.

Axiom surrogateMax : Z.

Axiom t1 : Z.

Axiom tx : Z.

Axiom t2 : Z.

Axiom t3 : Z.

Axiom t4 : Z.

Axiom t5 : Z.

Axiom maskx : Z.

Axiom mask2 : Z.

Axiom mask3 : Z.

Axiom mask4 : Z.

Axiom rune1Max : Z.

Axiom rune2Max : Z.

Axiom rune3Max : Z.

Axiom locb : Z.

Axiom hicb : Z.

Axiom xx : Z.

Axiom as' : Z.

Axiom s1 : Z.

Axiom s2 : Z.

Axiom s3 : Z.

Axiom s4 : Z.

Axiom s5 : Z.

Axiom s6 : Z.

Axiom s7 : Z.

Axiom runeErrorByte0 : val.

Axiom runeErrorByte1 : val.

Axiom runeErrorByte2 : val.

Definition first : go_string := "unicode/utf8.first"%go.

Axiom first'init : val.

Axiom acceptRange : go_type.

Definition acceptRanges : go_string := "unicode/utf8.acceptRanges"%go.

Axiom acceptRanges'init : val.

Definition FullRune : go_string := "unicode/utf8.FullRune"%go.

Definition FullRuneInString : go_string := "unicode/utf8.FullRuneInString"%go.

Definition DecodeRune : go_string := "unicode/utf8.DecodeRune"%go.

Definition DecodeRuneInString : go_string := "unicode/utf8.DecodeRuneInString"%go.

Definition DecodeLastRune : go_string := "unicode/utf8.DecodeLastRune"%go.

Definition DecodeLastRuneInString : go_string := "unicode/utf8.DecodeLastRuneInString"%go.

Definition RuneLen : go_string := "unicode/utf8.RuneLen"%go.

Definition EncodeRune : go_string := "unicode/utf8.EncodeRune"%go.

Definition encodeRuneNonASCII : go_string := "unicode/utf8.encodeRuneNonASCII"%go.

Definition AppendRune : go_string := "unicode/utf8.AppendRune"%go.

Definition appendRuneNonASCII : go_string := "unicode/utf8.appendRuneNonASCII"%go.

Definition RuneCount : go_string := "unicode/utf8.RuneCount"%go.

Definition RuneCountInString : go_string := "unicode/utf8.RuneCountInString"%go.

Definition RuneStart : go_string := "unicode/utf8.RuneStart"%go.

Definition Valid : go_string := "unicode/utf8.Valid"%go.

Definition ValidString : go_string := "unicode/utf8.ValidString"%go.

Definition ValidRune : go_string := "unicode/utf8.ValidRune"%go.

Definition vars' : list (go_string * go_type) := [].

Axiom encodeRuneNonASCIIⁱᵐᵖˡ : val.

Axiom AppendRuneⁱᵐᵖˡ : val.

Axiom appendRuneNonASCIIⁱᵐᵖˡ : val.

Axiom RuneStartⁱᵐᵖˡ : val.

Axiom ValidRuneⁱᵐᵖˡ : val.

Definition functions' : list (go_string * val) := [(FullRune, FullRuneⁱᵐᵖˡ); (FullRuneInString, FullRuneInStringⁱᵐᵖˡ); (DecodeRune, DecodeRuneⁱᵐᵖˡ); (DecodeRuneInString, DecodeRuneInStringⁱᵐᵖˡ); (DecodeLastRune, DecodeLastRuneⁱᵐᵖˡ); (DecodeLastRuneInString, DecodeLastRuneInStringⁱᵐᵖˡ); (RuneLen, RuneLenⁱᵐᵖˡ); (EncodeRune, EncodeRuneⁱᵐᵖˡ); (encodeRuneNonASCII, encodeRuneNonASCIIⁱᵐᵖˡ); (AppendRune, AppendRuneⁱᵐᵖˡ); (appendRuneNonASCII, appendRuneNonASCIIⁱᵐᵖˡ); (RuneCount, RuneCountⁱᵐᵖˡ); (RuneCountInString, RuneCountInStringⁱᵐᵖˡ); (RuneStart, RuneStartⁱᵐᵖˡ); (Valid, Validⁱᵐᵖˡ); (ValidString, ValidStringⁱᵐᵖˡ); (ValidRune, ValidRuneⁱᵐᵖˡ)].

Definition msets' : list (go_string * (list (go_string * val))) := [(acceptRange.id, []); (ptrT.id acceptRange.id, [])].

#[global] Instance info' : PkgInfo utf8.utf8 :=
  {|
    pkg_vars := vars';
    pkg_functions := functions';
    pkg_msets := msets';
    pkg_imported_pkgs := [];
  |}.

Axiom _'init : val.

Definition initialize' : val :=
  λ: <>,
    package.init #utf8.utf8 (λ: <>,
      exception_do (do:  (package.alloc utf8.utf8 #());;;
      do:  (first'init #());;;
      do:  (acceptRanges'init #()))
      ).

End code.
End utf8.
