(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.manualproof.unicode.utf8.
Require Export New.golang.theory.

Require Export New.code.unicode.utf8.

Set Default Proof Using "Type".

Module utf8.

(* type utf8.acceptRange *)
Module acceptRange.
Section def.
Context `{ffi_syntax}.
Axiom t : Type.
End def.
End acceptRange.

Global Instance bounded_size_acceptRange : BoundedTypeSize utf8.acceptRange.
Admitted.

Global Instance into_val_acceptRange `{ffi_syntax} : IntoVal acceptRange.t.
Admitted.

Global Instance into_val_typed_acceptRange `{ffi_syntax} : IntoValTyped acceptRange.t utf8.acceptRange.
Admitted.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_utf8 : IsPkgDefinedPure utf8 :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single utf8;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_utf8 : IsPkgDefined utf8 :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single utf8)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_func_call_FullRune :
  WpFuncCall utf8.FullRune _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_FullRuneInString :
  WpFuncCall utf8.FullRuneInString _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_DecodeRune :
  WpFuncCall utf8.DecodeRune _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_DecodeRuneInString :
  WpFuncCall utf8.DecodeRuneInString _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_DecodeLastRune :
  WpFuncCall utf8.DecodeLastRune _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_DecodeLastRuneInString :
  WpFuncCall utf8.DecodeLastRuneInString _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_RuneLen :
  WpFuncCall utf8.RuneLen _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_EncodeRune :
  WpFuncCall utf8.EncodeRune _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_RuneCount :
  WpFuncCall utf8.RuneCount _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_RuneCountInString :
  WpFuncCall utf8.RuneCountInString _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_RuneStart :
  WpFuncCall utf8.RuneStart _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_Valid :
  WpFuncCall utf8.Valid _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_ValidString :
  WpFuncCall utf8.ValidString _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_ValidRune :
  WpFuncCall utf8.ValidRune _ (is_pkg_defined utf8) :=
  ltac:(solve_wp_func_call).

End names.
End utf8.
